import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {chromium} from '@playwright/test';
import {adminClient,loadLocalEnv,config} from '../src/config.js';import {createClient} from '@supabase/supabase-js';import {mkdir,writeFile} from 'node:fs/promises';
loadLocalEnv();const db=adminClient(),cfg=config(),base=process.env.TEST_SITE||'http://127.0.0.1:4323',tag='qa-'+randomUUID().slice(0,8),password=randomUUID()+randomUUID(),email=tag+'@example.invalid';let userId='',brand='',person='',browser:any;const report:any[]=[];const ok=(r:any)=>{if(r.error)throw r.error;return r.data;};let token='';
async function api(path:string,b?:any,expected=200){const r=await fetch(base+'/api/'+path,{method:b===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(b===undefined?{}:{body:JSON.stringify(b)})});const data=await r.json();assert.equal(r.status,expected,path+': '+JSON.stringify(data));return data;}
function pass(name:string,detail:any=true){report.push({name,detail});console.log('PASS '+name+' '+JSON.stringify(detail));}
const client=createClient(cfg.SUPABASE_URL,cfg.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
async function waitJob(id:string){for(let i=0;i<120;i++){const result=await api('generate?id='+id);if(result.done){assert(!result.error,result.error);return result;}await new Promise(r=>setTimeout(r,3000));}throw Error('Generación no completada');}
try{
 userId=ok(await db.auth.admin.createUser({email,password,email_confirm:true})).user.id;ok(await db.from('miembros').insert({user_id:userId,rol:'admin',limite_mensual_usd:10}));token=ok(await client.auth.signInWithPassword({email,password})).session.access_token;
 brand=(await api('brands',{name:tag,defaults:{idioma:'Español',cta:'Escríbenos'},rules:'No inventar estadísticas.',profile:'Marca temporal de pruebas. Fotografía editorial.'})).id;
 let detail=await api('brands/'+brand);assert(detail.resources.conocimiento.length===1);pass('create brand and profile');
 detail=await api('brands/'+brand,{version:detail.version,name:tag+' editada',datos:[{dato:'Prueba aprobada',fuente:'Equipo',url:''}]});assert(detail.datos.length===1);pass('edit brand and facts');
 person=(await api('people',{name:tag,aliases:['QA'],descripcion:'Persona de prueba',brands:[brand]})).id;assert((await api('people')).some((p:any)=>p.id===person&&p.brands.includes(brand)));pass('people + brand associations');
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=','base64');
 async function upload(scope:any){const up=await api('assets/upload',{...scope,name:tag+'.png',mime:'image/png',bytes:png.length});ok(await client.storage.from('estudio').uploadToSignedUrl(up.path,up.token,png,{contentType:'image/png'}));await api('assets/finalize',{id:up.id});return up.id;}
 const photo=await upload({person});await api('people/'+person+'/photo',{op:'add',fileId:photo});await api('people/'+person+'/photo',{op:'update',photo,active:false});await api('people/'+person+'/photo',{op:'update',photo,active:true});pass('person photo upload + activation');
 const asset=await upload({brand});detail=await api('brands/'+brand+'/add',{kind:'logos',fileId:asset,role:'dark'});assert(detail.logos.dark.url==='storage://'+asset);pass('logo upload + assignment');
 const path=detail.resources.conocimiento[0].path;detail=await api('brands/'+brand+'/update',{path,text:'Texto editado.',tags:['test'],active:false});assert(detail.resources.conocimiento[0].active===false);await api('brands/'+brand+'/delete',{path});detail=await api('brands/'+brand);assert(detail.trash.length===1);await api('brands/'+brand+'/restore',{name:detail.trash[0].name});pass('edit/delete/restore document');
 const req=await api('requests',{brief:{marca:brand,tema:'Prueba',laminas:'1'},status:'nueva'});await api('requests',{...req,status:'produccion'});assert((await api('requests')).some((r:any)=>r.id===req.id&&r.status==='produccion'));pass('request create and update');
 const doc={id:tag,brand,name:tag,slides:[{layout:'frase',theme:'light',title:'Auditoría de *prueba*',body:'Texto temporal',photo:'Un escritorio con luz natural',photoPrompt:'A real wooden desk beside a window, natural editorial photograph, no text'}]};await api('projects',{...doc,version:0});await api('projects',{...doc,version:0},409);pass('project create and stale conflict');
 const signed=await api('assets/sign-batch',{ids:[asset]});assert((await fetch(signed.urls[asset])).ok);pass('batch signing and image download');
 browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(30000);const errors:string[]=[];page.on('pageerror',(e:any)=>errors.push(e.message));if(process.env.DEBUG_BROWSER)page.on('console',(m:any)=>console.log('BROWSER '+m.type()+' '+m.text().slice(0,200)));page.on('requestfailed',(r:any)=>{if(r.url().includes('/storage/'))console.log('STORAGE FAILED '+r.failure()?.errorText);});
 await page.goto(base+'/?view=editor&p='+tag);await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('#login-form button')!.disabled);await page.getByLabel('Email',{exact:true}).fill(email);await page.getByLabel('Contraseña',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar al Estudio'}).click();await page.waitForSelector('#stage-inner .slide');
 await page.evaluate(()=>{const w=window as any;return w.cloudApi('/api/projects').then((p:any)=>{if(!p.length)throw Error('No projects');});});pass('browser authenticated editor');
 await page.locator('#p-name').fill(tag+'-browser');await page.waitForFunction(()=>document.querySelector('#save-state')!.textContent!.startsWith('Guardado'));assert.equal((await api('projects?id='+tag)).name,tag+'-browser');pass('browser edit persisted');
 await page.locator('#exp-scale').selectOption('1');await page.locator('#btn-export-all').click();await page.waitForFunction(()=>document.querySelector('#exp-title')!.textContent==='Lámina exportada'||document.querySelector('#exp-title')!.textContent==='La exportación falló');assert.equal(await page.locator('#exp-title').innerText(),'Lámina exportada');assert(!(await page.locator('#exp-msg').innerText()).startsWith('Guardado en /'));console.log('Export folder: '+await page.locator('#exp-msg').innerText());await page.evaluate(()=>document.querySelector<HTMLDialogElement>('#dlg-export')!.close());pass('real PNG export + correct folder');
 await page.locator('.tab[data-view=deliveries]').click();await page.locator('#deliv-list img').first().waitFor();await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('#deliv-list img')].some(i=>i.complete&&i.naturalWidth>0));pass('delivery gallery images render');
 await page.locator('.tab[data-view=brands]').click();await page.locator('#mk-identity').waitFor();assert(!(await page.locator('#mk-main').innerText()).includes('Ruta no disponible'));pass('brand detail renders');
 await page.locator('[data-type=people]').click();await page.locator('#mk-new-person').waitFor();pass('people page renders');
 if(process.argv.includes('--cutout')){
  await page.locator('.tab[data-view=editor]').click();const approved=(await api('people')).find((p:any)=>p.photos?.length&&p.id!==person);assert(approved,'Need an existing approved photo for segmentation');
  const result=await page.evaluate(async(ref:string)=>{const w=window as any;const out=await Promise.race([w.cloudApi('/api/cutout',{url:ref}),new Promise((_,reject)=>setTimeout(()=>reject(Error('Recorte timeout 45s')),45000))]) as any;const img=new Image();img.crossOrigin='anonymous';img.src=out.cutout;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(img,0,0);const pixels=ctx.getImageData(0,0,img.width,img.height).data;let transparent=0,opaque=0;for(let i=3;i<pixels.length;i+=4){if(pixels[i]!<20)transparent++;if(pixels[i]!>230)opaque++;}return {width:img.width,height:img.height,transparent:transparent/(pixels.length/4),opaque:opaque/(pixels.length/4)};},approved.photos[0].url);assert(result.transparent>.01&&result.opaque>.01,JSON.stringify(result));pass('real person cutout with alpha',result);
  const saved=await api('projects?id='+tag);saved.slides=[{...saved.slides[0],layout:'portada',image:approved.photos[0].url},{...saved.slides[0],layout:'escena',image:approved.photos[0].url,title:'Segunda lámina'}];await api('projects',saved);await page.reload();await page.waitForSelector('#stage-inner .slide');await page.locator('#exp-scale').selectOption('1');await page.locator('#btn-export-all').click();await page.waitForFunction(()=>/exportad|falló/.test(document.querySelector('#exp-title')!.textContent||''),{},{timeout:60000});assert(!(await page.locator('#exp-title').innerText()).includes('falló'),await page.locator('#exp-msg').innerText());assert.equal(await page.locator('#exp-title').innerText(),'Carrusel exportado');await page.evaluate(()=>document.querySelector<HTMLDialogElement>('#dlg-export')!.close());pass('two-slide carousel export with real person image');
 }
 await page.locator('.tab[data-view=editor]').click();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,elements:[...document.querySelectorAll('#studio-shell *')].filter(e=>e.getBoundingClientRect().right>innerWidth+2&&e.getBoundingClientRect().width>0).slice(0,8).map(e=>({id:e.id,cls:e.className,width:e.getBoundingClientRect().width}))}));assert(overflow.scroll<=overflow.width,JSON.stringify(overflow));pass('mobile no horizontal overflow');
 assert.deepEqual(errors,[]);pass('no browser JavaScript errors');
 // Exercise roles on the same authenticated token: current membership must be enforced.
 ok(await db.from('miembros').update({rol:'lector'}).eq('user_id',userId));ok(await db.from('miembro_marca').insert({user_id:userId,marca_id:brand}));await api('brands/'+brand,{name:'denied'},403);await api('requests',{brief:{marca:brand}},403);await api('people',{name:'denied'},403);ok(await db.from('miembros').update({rol:'admin'}).eq('user_id',userId));pass('reader writes denied');
 if(process.argv.includes('--profile')){const q=await api('brands/_draft',{name:'Taller de prueba',description:'Un taller de cerámica artesanal. Tono cercano; tonos tierra. No inventar datos.',idempotencyKey:randomUUID()},202);const result=await waitJob(q.id);assert(result.result.profile&&result.result.rules&&result.result.accent);pass('real Claude brand profile',{usd:result.result.usage.usd});}
 if(process.argv.includes('--ai')){
  const key=randomUUID(),b={marca:brand,idea:'Un post sobre ordenar el escritorio sin cifras.',tema:'Ordenar el escritorio',laminas:'1',idioma:'Español',idempotencyKey:key};const q=await api('propose',b,202);assert.equal((await api('propose',b,202)).id,q.id);const result=await waitJob(q.id);assert.equal(result.result.slides.length,1);pass('real Claude proposal + idempotency',{slides:result.result.slides.length,usd:result.result.usage.usd});
  const image=await api('generate',{projectId:tag,motor:'hf_flare',tamano:'1k',items:[{index:0,prompt:doc.slides[0]!.photoPrompt,people:[],slide:doc.slides[0]}],idempotencyKey:randomUUID()},202);const images=await waitJob(image.id);assert(images.items[0].url.startsWith('storage://'));pass('real Higgsfield image',images.items[0].status);
  const reopened=await api('projects?id='+tag);assert.equal(reopened.slides[0].image,images.items[0].url);pass('generated image recovered on reopen');
 }
 await api('people/'+person+'/archive',{});await api('brands/_restore',{name:'persona:'+person});await api('brands/'+brand+'/archive',{});await api('brands/_restore',{name:'marca:'+brand});pass('archive and restore brands/people');
}catch(e:any){report.push({error:e.message});console.error('FAIL',e.message);process.exitCode=1;}
finally{
 await browser?.close();if(brand!){ok(await db.from('trabajos').delete().eq('marca_id',brand));ok(await db.from('auditoria').delete().eq('marca_id',brand));ok(await db.from('solicitudes').delete().eq('marca_id',brand));ok(await db.from('proyectos').delete().eq('marca_id',brand));ok(await db.from('entregas').delete().eq('marca_id',brand));ok(await db.from('marca_recursos').delete().eq('marca_id',brand));ok(await db.from('marca_datos').delete().eq('marca_id',brand));}
 if(person!){ok(await db.from('persona_fotos').delete().eq('persona_id',person));ok(await db.from('persona_marca').delete().eq('persona_id',person));}
 if(brand!||person!){const files=ok(await db.from('archivos').select('id,object_path').or([brand&&'marca_id.eq.'+brand,person&&'persona_id.eq.'+person].filter(Boolean).join(',')));if(files.length){ok(await db.storage.from('estudio').remove(files.map((f:any)=>f.object_path)));ok(await db.from('archivos').delete().in('id',files.map((f:any)=>f.id)));}}
 if(person!)ok(await db.from('personas').delete().eq('id',person));if(brand!)ok(await db.from('marcas').delete().eq('id',brand));if(userId!){ok(await db.from('auditoria').delete().eq('actor_id',userId));ok(await db.from('trabajos').delete().eq('user_id',userId));ok(await db.from('miembros').delete().eq('user_id',userId));await client.auth.signOut();ok(await db.auth.admin.deleteUser(userId));}pass('temporary data removed');await mkdir('artifacts',{recursive:true});await writeFile('artifacts/functional-report.json',JSON.stringify(report,null,2));
}
