import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const A='00000000-0000-4000-a000-000000000001', E='00000000-0000-4000-a000-000000000002',L='00000000-0000-4000-a000-000000000003', B='00000000-0000-4000-a000-000000000004';
test('Postgres real: aislamiento, privilegios, versiones y cola',async t=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth to authenticated,service_role;
 grant execute on function auth.uid() to authenticated,service_role;
 create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select on storage.objects to authenticated;`);
 for(const file of (await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(f=>f.endsWith('.sql')).sort()) await db.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
 await db.exec(`insert into auth.users values('${A}'),('${E}'),('${L}'),('${B}');
 insert into miembros(user_id,rol,limite_mensual_usd) values('${A}','admin',25),('${E}','editor',1),('${L}','lector',25),('${B}','editor',25);
 insert into marcas(id) values('eva'),('janica'),('_comun');
 insert into miembro_marca values('${E}','eva'),('${L}','eva'),('${B}','janica');
 insert into personas(id) values('persona-eva');insert into persona_marca values('persona-eva','eva');
 insert into proyectos(id,marca_id,documento) values('p-eva','eva','{"id":"p-eva","brand":"eva","slides":[]}'),('p-janica','janica','{"id":"p-janica","brand":"janica"}');
 insert into archivos(id,alcance,marca_id,nombre,mime,bytes,listo) values('10000000-0000-4000-a000-000000000001','marca','eva','foto','image/png',10,true),('10000000-0000-4000-a000-000000000002','marca','janica','foto','image/png',10,true);
 insert into archivos(id,alcance,nombre,mime,bytes,listo) values('10000000-0000-4000-a000-000000000003','cuarentena','privado','image/png',10,true);
 insert into storage.objects(bucket_id,name) select 'estudio',object_path from archivos;`);
 async function as(role:string,id=''){await db.exec(`reset role;set role ${role};select set_config('request.jwt.claim.sub','${id}',false);`);}
 const rows=async(sql:string)=>(await db.query<any>(sql)).rows;
 await t.test('editor ve su marca y documentos comunes; no otra marca ni su persona',async()=>{await as('authenticated',E);assert.deepEqual((await rows('select id from marcas order by id')).map(r=>r.id),['_comun','eva']);assert.equal((await rows('select * from proyectos')).length,1);await as('authenticated',B);assert.equal((await rows('select * from personas')).length,0);});
 await t.test('anónimo no puede consultar datos',async()=>{await as('anon');await assert.rejects(db.query('select * from marcas'),/permission denied/);});
 await t.test('editor no cambia su rol, presupuesto ni asignaciones',async()=>{await as('authenticated',E);await assert.rejects(db.query(`update miembros set rol='admin' where user_id='${E}'`),/permission denied/);await assert.rejects(db.query(`insert into miembro_marca values('${E}','janica')`),/permission denied/);});
 await t.test('storage no filtra fotos de otra marca ni cuarentena',async()=>{await as('authenticated',E);assert.equal((await rows('select * from storage.objects')).length,1);await as('authenticated',A);assert.equal((await rows('select * from storage.objects')).length,3);});
 await t.test('lector no puede guardar',async()=>{await as('authenticated',L);await assert.rejects(db.query(`select guardar_proyecto('nuevo','eva','{"id":"nuevo","brand":"eva"}',0)`),/row-level security/);});
 await t.test('guardar con versión actual y rechazar un guardado obsoleto',async()=>{await as('authenticated',E);await db.query(`select guardar_proyecto('p-eva','eva','{"id":"p-eva","brand":"eva","name":"nuevo"}',1)`);assert.equal((await rows("select version from proyectos where id='p-eva'"))[0].version,2);await assert.rejects(db.query(`select guardar_proyecto('p-eva','eva','{"id":"p-eva","brand":"eva","name":"pisar"}',1)`),/modificado/);});
 await t.test('REST directo tampoco evita el control de versiones',async()=>{await as('authenticated',E);await assert.rejects(db.query(`update proyectos set documento='{"id":"p-eva","brand":"eva"}' where id='p-eva'`),/Conflicto de versión/);});
 await t.test('no se puede reasignar proyecto a otra marca o falsificar JSON',async()=>{await as('authenticated',E);await assert.rejects(db.query(`update proyectos set marca_id='janica',version=version+1 where id='p-eva'`),/permission denied/);await assert.rejects(db.query(`select guardar_proyecto('p-eva','eva','{"id":"p-eva","brand":"janica"}',2)`),/Identidad del documento/);});
 await t.test('no se puede asociar un archivo de otra marca',async()=>{await as('service_role');await assert.rejects(db.query(`insert into marca_recursos(marca_id,archivo_id,tipo,ruta) values('eva','10000000-0000-4000-a000-000000000002','logos','logo.png')`),/foreign key/);});
 const enqueue=(actor=E,key='20000000-0000-4000-a000-000000000001',cost=.6,brand='eva')=>`select (encolar_trabajo('${actor}','${brand}','imagen','test','{}','${key}','hash',${cost},'30000000-0000-4000-a000-000000000001')).id`;
 await t.test('cliente no puede inventar precios ni reclamar la cola',async()=>{await as('authenticated',E);await assert.rejects(db.query(enqueue()),/permission denied/);await assert.rejects(db.query('select reclamar_trabajo()'),/permission denied/);await assert.rejects(db.query("update trabajos set coste_usd=0"),/permission denied/);});
 await t.test('servidor verifica marca y lector antes de reservar',async()=>{await as('service_role');await assert.rejects(db.query(enqueue(L)),/Sin permiso/);await assert.rejects(db.query(enqueue(E,undefined,.6,'janica')),/Marca no autorizada/);});
 await t.test('idempotencia devuelve mismo trabajo y conserva una reserva',async()=>{await as('service_role');const first=await rows(enqueue());const second=await rows(enqueue());assert.equal(first[0].id,second[0].id);assert.equal((await rows('select count(*)::int n from trabajos'))[0].n,1);});
 await t.test('reutilizar la clave para otro payload se rechaza',async()=>{await as('service_role');await assert.rejects(db.query(enqueue().replace("'{}'","'{\"otro\":true}'")),/otra solicitud/);});
 await t.test('reserva pendiente cuenta contra el límite mensual',async()=>{await as('service_role');await assert.rejects(db.query(enqueue(E,'20000000-0000-4000-a000-000000000002')),/Presupuesto mensual/);});
 await t.test('claim no duplica trabajo; timeout sin provider pasa a incierto',async()=>{await as('service_role');const claimed=await rows('select * from reclamar_trabajo()');assert.equal(claimed.length,1);assert.equal((await rows('select * from reclamar_trabajo()')).length,0);await db.exec("update trabajos set lease_until=now()-interval '1 minute'");assert.equal((await rows('select * from reclamar_trabajo()')).length,0);assert.equal((await rows('select estado from trabajos'))[0].estado,'uncertain');});
 await t.test('presupuesto incierto se mantiene al cambiar de mes',async()=>{await as('service_role');await db.exec("update trabajos set created_at=now()-interval '2 months'");await assert.rejects(db.query(enqueue(E,'20000000-0000-4000-a000-000000000003')),/Presupuesto mensual/);});
 await t.test('usuario suspendido pierde acceso inmediatamente',async()=>{await as('service_role');await db.exec(`update miembros set activo=false where user_id='${E}'`);await as('authenticated',E);assert.equal((await rows('select * from marcas')).length,0);assert.equal((await rows('select * from storage.objects')).length,0);});
 await t.test('RLS habilitado en todas las tablas de aplicación',async()=>{await as('service_role');assert.equal((await rows("select relname from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity")).length,0);});
 await db.close();
});
