import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
import {adminClient} from './config.js';
import {authorizeBrand,HttpError,type Identity} from './auth.js';
import {adminOnly,checked,brandDetail,storeFile} from './library.js';
import {prompts} from './prompts.js';
export function aiConfig(){const enabled=!!process.env.HF_CREDENTIALS;return {hasKey:!!process.env.ANTHROPIC_API_KEY,fromEnv:true,motores:[{id:'hf_flare',nombre:'GPT Image 2.5 Flare',proveedor:'Higgsfield',env:'HF_CREDENTIALS',disponible:enabled,tamanos:{'1k':null,'2k':null,'4k':null}}],motorDefecto:'hf_flare',tamanoDefecto:'2k',reservationPerImage:2,reservationPerProposal:2};}
const digest=(x:any)=>createHash('sha256').update(JSON.stringify(x)).digest('hex');
function childKey(group:string,index:number){const h=digest([group,index]).slice(0,32);return `${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20)}`;}
export async function enqueue(w:Identity,route:string,b:any){
 const key=z.uuid().parse(b.idempotencyKey),jobs:any[]=[];let brand:string;
 if(route==='generate'){
  if(!process.env.HF_CREDENTIALS)throw new HttpError(503,'El proveedor de imágenes no está configurado.');if(b.motor&&b.motor!=='hf_flare')throw new HttpError(400,'Elige GPT Image 2.5 Flare, disponible en este Estudio.');
  const p=checked(await w.db.from('proyectos').select('*').eq('id',z.string().max(128).parse(b.projectId)).maybeSingle());if(!p)throw new HttpError(404,'Guarda primero el proyecto.');brand=p.marca_id;await authorizeBrand(w,brand,true);
  const items=z.array(z.object({index:z.number().int().min(0).max(29),prompt:z.string().max(12000),people:z.array(z.any()).optional(),slide:z.record(z.string(),z.any()).optional(),count:z.string().max(20).optional()}).passthrough()).min(1).max(10).parse(b.items);if(new Set(items.map(i=>i.index)).size!==items.length)throw new HttpError(400,'Láminas duplicadas.');
  for(const item of items){const slide=p.documento.slides[item.index];if(!slide)throw new HttpError(400,'Lámina inválida.');const payload={...item,originalImage:slide.image||'',tamano:z.enum(['1k','2k','4k']).parse(b.tamano||'2k'),slide:{...slide,...item.slide}};jobs.push({tipo:'imagen',motor:'hf_flare',payload,key:childKey(key,item.index),hash:digest(payload),reserva:2,proyecto:p.id,lamina:String(item.index),version:p.version});}
 }else{
  if(!process.env.ANTHROPIC_API_KEY)throw new HttpError(503,'Anthropic no está configurado.');if(route==='brands/_draft'){adminOnly(w);brand='_comun';}else brand=z.string().min(1).parse((b.brief||b).marca);
  await authorizeBrand(w,brand,true);const {idempotencyKey,...payload}=b;if(JSON.stringify(payload).length>20000)throw new HttpError(400,'El brief es demasiado largo.');
  jobs.push({tipo:route==='brands/_draft'?'perfil':'propuesta',motor:'claude-sonnet-4-6',payload,key,hash:digest(payload),reserva:2});
 }
 const r=await adminClient().rpc('encolar_lote',{p_actor:w.id,p_marca:brand,p_grupo:key,p_jobs:jobs});if(r.error){if(r.error.code==='P0001')throw new HttpError(409,'No hay presupuesto disponible o hay demasiados trabajos pendientes. Revisa los trabajos antes de generar de nuevo.');checked(r);}return {id:r.data![0].grupo_id,jobId:r.data![0].id,queued:true};
}
export async function generationStatus(w:Identity,group:string){const rows=checked(await w.db.from('trabajos').select('id,estado,resultado,error,lamina_id,motor,payload').eq('grupo_id',z.uuid().parse(group)).order('created_at'));if(!rows.length)throw new HttpError(404,'Trabajo no encontrado.');const done=rows.every((x:any)=>['succeeded','failed','uncertain','canceled'].includes(x.estado));return {id:group,done,items:rows.map((j:any)=>({index:Number(j.lamina_id??0),status:j.estado==='succeeded'?'completed':['failed','uncertain','canceled'].includes(j.estado)?'failed':j.estado,...j.resultado,error:j.error,motor:j.motor,tamano:j.payload.tamano})),result:done&&rows.length===1?rows[0].resultado:null,error:done?rows.find((x:any)=>x.error)?.error:null};}
async function saveJob(j:any,patch:any){const r=await adminClient().from('trabajos').update({...patch,updated_at:new Date().toISOString(),lease_token:null,lease_until:null}).eq('id',j.id).eq('lease_token',j.lease_token).select('id');checked(r);if(!r.data?.length)throw new Error('Lease vencido');}
class ProviderError extends Error{constructor(public status:number){super(`Proveedor respondió ${status}`);}}
async function jsonFetch(url:string,init:any,timeout=45000){const r=await fetch(url,{...init,signal:AbortSignal.timeout(timeout),redirect:'error'});if(!r.ok)throw new ProviderError(r.status);return r.json();}
const hf=(path:string,b?:any)=>jsonFetch('https://api.higgsfield.ai/'+path,{method:b?'POST':'GET',headers:{Authorization:'Key '+process.env.HF_CREDENTIALS,'Content-Type':'application/json'},...(b?{body:JSON.stringify(b)}:{})});
async function workerIdentity(j:any):Promise<Identity>{const db=adminClient();const m=checked(await db.from('miembros').select('*').eq('user_id',j.user_id).single());if(!m?.activo||!['admin','editor'].includes(m.rol))throw new HttpError(403,'Acceso revocado.');if(m.rol!=='admin'){const link=checked(await db.from('miembro_marca').select('*').eq('user_id',j.user_id).eq('marca_id',j.marca_id).maybeSingle());if(!link||j.marca_id==='_comun')throw new HttpError(403,'Acceso revocado.');}const brand=checked(await db.from('marcas').select('archivada').eq('id',j.marca_id).single());if(brand.archivada)throw new HttpError(403,'Marca archivada.');return {id:j.user_id,role:m.rol,db};}
async function fileUrl(ref:string){if(!/^storage:\/\/[0-9a-f-]{36}$/.test(ref))throw new Error('Referencia inválida');const id=ref.slice(10);const f=checked(await adminClient().from('archivos').select('object_path,listo,eliminado_at').eq('id',id).single());if(!f.listo||f.eliminado_at)throw new Error('Archivo no disponible');return checked(await adminClient().storage.from('estudio').createSignedUrl(f.object_path,3600)).signedUrl;}
async function knowledge(w:Identity,brand:string){const all=[await brandDetail(w,brand)];if(brand!=='_comun')all.push(await brandDetail(w,'_comun'));let text='',remaining=80000;const media:any[]=[];let visualCount=0,pdfCount=0;
 for(const d of all){for(const ref of d.resources.referencias.filter((r:any)=>r.active)){if(visualCount>=6)break;if(ref.size<=4500000){media.push({type:'image',source:{type:'url',url:await fileUrl(ref.url)}});visualCount++;}}text+=`\nMarca: ${d.name}\nReglas: ${d.rules}\nDatos verificados: ${JSON.stringify(d.datos)}\nPersonas aprobadas: ${JSON.stringify(d.people.map((p:any)=>({id:p.id,name:p.name,descripcion:p.descripcion})))}`;
  for(const f of d.resources.conocimiento.filter((f:any)=>f.active)){if(remaining<=0)break;const file=checked(await w.db.from('archivos').select('*').eq('id',f.url.slice(10)).single());if(file.mime==='application/pdf'&&pdfCount<2&&file.bytes<1500000){const b=checked(await adminClient().storage.from('estudio').download(file.object_path));pdfCount++;media.push({type:'document',source:{type:'base64',media_type:'application/pdf',data:Buffer.from(await b.arrayBuffer()).toString('base64')}});}else if(file.mime.startsWith('text/')&&file.bytes<500000){const b=checked(await adminClient().storage.from('estudio').download(file.object_path));const content=(await b.text()).slice(0,remaining);remaining-=content.length;text+=`\nDocumento ${f.name}:\n${content}`;}}
 }
 return {text:text.slice(0,100000),media};
}
async function textJob(j:any,w:Identity){const profile=j.tipo==='perfil',k=await knowledge(w,j.marca_id),brief=j.payload.brief||j.payload;const schema=profile?prompts.brand_schema:prompts.draft_schema;
 const messages=[{role:'user',content:[...k.media,{type:'text',text:`Fecha: ${new Date().toISOString().slice(0,10)}\nBrief: ${JSON.stringify(brief)}\nInvestiga solo si necesitas verificar hechos o el sitio web indicado. Nunca inventes cifras ni afirmes que has consultado fuentes que no consultaste. Devuelve el contenido con el esquema solicitado.`}]}];
 const data=await jsonFetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':process.env.ANTHROPIC_API_KEY!,'anthropic-version':'2023-06-01','Content-Type':'application/json'},body:JSON.stringify({model:'claude-sonnet-4-6',max_tokens:10000,system:(profile?prompts.brand_rules:prompts.draft_rules)+'\n'+k.text,tools:[{type:'web_search_20250305',name:'web_search',max_uses:2}],messages,output_config:{format:{type:'json_schema',schema}}})},240000);
 if(data.stop_reason==='max_tokens'||data.stop_reason==='refusal')throw new Error('La propuesta no pudo completarse.');const raw=data.content.filter((x:any)=>x.type==='text').map((x:any)=>x.text).join('');const result=JSON.parse(raw);if(!profile)z.array(z.object({title:z.string(),layout:z.string()}).passthrough()).min(1).max(30).parse(result.slides);
 const usage=data.usage||{};const usd=(usage.input_tokens||0)*3e-6+(usage.output_tokens||0)*15e-6+(usage.server_tool_use?.web_search_requests||0)*0.01;
 result.usage={usd,model:data.model,...usage};result.research=data.content.filter((x:any)=>x.type==='web_search_tool_result').flatMap((x:any)=>Array.isArray(x.content)?x.content.map((r:any)=>`${r.title||''} ${r.url||''}`):[]).join('\n');await saveJob(j,{estado:'succeeded',error:null,resultado:result,coste_usd:usd});
}
async function imageJob(j:any,w:Identity){const db=adminClient();let data;
 if(!j.provider_id){const brand=await brandDetail(w,j.marca_id),p=j.payload,s=p.slide||{};const wanted=new Set((p.people||[]).map((x:any)=>typeof x==='string'?x:x.id));const mentioned=(p.prompt+' '+(s.photo||'')).toLowerCase();const people=brand.people.filter((x:any)=>wanted.has(x.id)||[x.name,...x.aliases].some((n:string)=>mentioned.includes(n.toLowerCase())));const refs:string[]=[];
  for(const person of people.slice(0,2)){const photos=person.photos.filter((f:any)=>f.active);const preferred=s.basePhoto||person.fotos_base?.[s.layout]||person.fotos_base?.otras;photos.sort((a:any,b:any)=>Number(b.name===preferred||b.label===preferred)-Number(a.name===preferred||a.label===preferred));for(const f of photos.slice(0,2))refs.push(await fileUrl(f.url));}
  const outfits=brand.outfits||[];if(people.length&&s.outfit!=='original'&&outfits.length){const outfit=outfits.find((x:any)=>x.name===s.outfit||x.path===s.outfit)||outfits[p.index%outfits.length];refs.push(await fileUrl(outfit.url));}
  const full=brand.modo==='completa';let prompt=p.prompt+'\n'+(brand.look||'')+'\n'+people.map((x:any)=>x.lock).join('\n');
  if(people.length)prompt+='\nUse the first reference images for the exact approved identity. Preserve face and natural skin texture. '+(refs.length>people.length*2?'The last reference specifies clothing only.':'');
  if(full){prompt+=`\nCreate a finished Spanish editorial Instagram slide. Render these exact texts with correct accents: ${JSON.stringify(s)}. Brand palette and type: ${JSON.stringify({colors:brand.colors,fonts:brand.fonts})}. Large readable title, polished editorial layout, 4:5 safe composition. No invented words or logos. Slide ${p.count||''}.`;const visual=brand.resources.referencias.filter((r:any)=>r.active).slice(0,2);for(const ref of visual)if(refs.length<6)refs.push(await fileUrl(ref.url));}
  else prompt+='\nNo text, letters, logos or watermark. Leave space for the title. Natural editorial photography.';
  data=await hf('marketing-studio/image/flare',{prompt:prompt.slice(0,20000),resolution:p.tamano,aspect_ratio:'3:4',quality:'high',enhance_prompt:false,...(refs.length?{image_urls:refs}:{})});
  const requestId=z.string().regex(/^[a-zA-Z0-9_-]{1,128}$/).parse(data.request_id);checked(await db.from('trabajos').update({provider_id:requestId,resultado:{full,needsCutout:!!brand.cutout&&!full}}).eq('id',j.id).eq('lease_token',j.lease_token));j.provider_id=requestId;j.resultado={full,needsCutout:!!brand.cutout&&!full};
 }else data=await hf('requests/'+encodeURIComponent(j.provider_id)+'/status');
 if(['failed','nsfw','canceled','cancelled'].includes(data.status)){await saveJob(j,{estado:'failed',error:'El proveedor no completó la imagen ('+data.status+').',coste_usd:0});return;}
 if(data.status!=='completed'){await saveJob(j,{estado:'waiting',next_run_at:new Date(Date.now()+4000).toISOString()});return;}
 const src=data.images?.[0]?.url||data.output?.images?.[0]?.url;const u=new URL(z.url().parse(src));if(u.protocol!=='https:')throw new Error('URL de proveedor inválida');
 // Only fetch provider-returned output, never a user-supplied URL.
 const r=await fetch(u,{signal:AbortSignal.timeout(45000),redirect:'error'});if(!r.ok)throw new Error('No se pudo descargar la imagen generada.');const bytes=Buffer.from(await r.arrayBuffer());const mime=r.headers.get('content-type')?.split(';')[0]||'image/png';if(!['image/png','image/jpeg','image/webp'].includes(mime))throw new Error('Formato inesperado.');const id=await storeFile(j.marca_id,bytes,mime,'generada-'+j.id+(mime==='image/png'?'.png':mime==='image/webp'?'.webp':'.jpg'));
 await saveJob(j,{estado:'succeeded',error:null,resultado:{url:'storage://'+id,cutout:'',full:!!j.resultado?.full,needsCutout:!!j.resultado?.needsCutout,motor:j.motor,tamano:j.payload.tamano},coste_usd:null});
}
export async function runWorker(maxJobs=3){const started=Date.now();for(let i=0;i<maxJobs;i++){if(Date.now()-started>40000)return;const rows=checked(await adminClient().rpc('reclamar_trabajo'));const j=rows?.[0];if(!j)return;let submitted=!!j.provider_id;
 try{if(j.provider_id&&Date.now()-Date.parse(j.created_at)>86400000){await saveJob(j,{estado:'uncertain',error:'El proveedor lleva más de 24 horas sin resultado confirmado. Revisa el trabajo antes de repetir.',coste_usd:null});continue;}const w=await workerIdentity(j);submitted=true;if(j.tipo==='imagen')await imageJob(j,w);else await textJob(j,w);}
 catch(e){const latest=checked(await adminClient().from('trabajos').select('provider_id').eq('id',j.id).single());const providerId=latest?.provider_id;const rejected=e instanceof ProviderError&&e.status>=400&&e.status<500&&e.status!==408;
 const safe=(e instanceof HttpError||rejected)&&!providerId;const waiting=!!providerId&&!(e instanceof HttpError);const error=e instanceof HttpError?e.message:rejected?`El proveedor rechazó la solicitud (${(e as ProviderError).status}). Revisa saldo y acceso del proveedor.`:waiting?'Esperando resultado del proveedor.':'Ejecución incierta. No se reenviará para evitar un cobro duplicado; revisa el proveedor.';
 await saveJob(j,{estado:waiting?'waiting':safe||!submitted?'failed':'uncertain',error,coste_usd:safe||!submitted?0:null,next_run_at:new Date(Date.now()+15000).toISOString()});}
 }}
// Recover completed images on reopen without overwriting a slide the user has replaced.
export async function recoveredProject(w:Identity,row:any){const jobs=checked(await w.db.from('trabajos').select('lamina_id,payload,resultado').eq('proyecto_id',row.id).eq('estado','succeeded').eq('tipo','imagen').order('created_at',{ascending:false}));const doc=structuredClone(row.documento),seen=new Set();for(const j of jobs){const i=Number(j.lamina_id);if(seen.has(i))continue;seen.add(i);const s=doc.slides?.[i];if(s&&(s.image||'')===(j.payload.originalImage||'')&&j.resultado?.url)Object.assign(s,{...j.resultado,image:j.resultado.url});}return {...doc,version:row.version};}
